# Generated by Django 3.2.3 on 2021-06-10 14:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.webp', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
